def display_bookworm

puts "
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXNWMMXkdddddxxxdodKWWKkxkkkxxkkxxkKNMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0xxxxxkkxxxxkxlo0XXXXNNXNKdldddkOKKXXXXKKOkxdkNMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxddxO0KXXXXXXK0kocd0XXXXXXXNXx:o0KKXNNWWWWWNXKK0do0W
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoxKKKKXNWWWMWWNXXK0xlkXNXXXXXkoOXKXWMMMMMMMMMMWXKKOok
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWko0XKKXWMMMMMMMMMMWNKKOoxXXXKXOlkXKNMMMMMMWX000XWMNKKkl
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0oOXKNMMMMMMMWKkxk0NWNKKkclxxxxloKKKWMMMMWOc....'l0WXKKl
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWdoXKKWMMMMMW0c.   .,xNXKXOdxxxxx0NKXMMMMWO'       ;0XKXo
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWdoXKXMMMMMMK,       .xXKXkoxkkkodKXKWMMMWx. ,l:.  .kKK0l
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkoKXKNMMMMM0,  .lOd'.d0KOlxXXXNKodXKKNMMMXl,dXO, .o0KKdo
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXddKXKXNMMMWk;..lkdcoOKKooKXXXXX0odKXKXNWMN0xxdlok0XKddK
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdo0XKKKNWMMXOdddxk0KOc:dxxkkkkkdccx0KXXXXXXXXXXK0xokNM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx:lxkOKXXXXXXXXXXKOdloxOkkOKKkoxOOxddxkOO00Okkxdo:xWMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKlxKkddxxkkkOOkkkxddOKXN0c.c0Kl.:OXXXKOkxxkkxxkOKKooXMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOlONXXXK0kdodxxkk0KXXXXXKkokKX0O0XXXXXNXXNN00XNXXXxoKMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOlONXXXXXNOokXXXNXXXXXXXXXNXNNNXXXXXXXXXXXKooKXXX0lxWMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXodKXNXXNXKxlxKXXXXXXXXXXXXXXXXXXXXXNNXXKOdoOXXX0odXMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKod0XXXXXXXOdodxO0KXXXXXXXXXXXXK00OOxxdddkKXX0dlxNMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkoodOKXXXXXKOo;:loooooollodxxxddxxxk0KXXKkdoxKWMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOxddxOKXXXk:lxddddol;lOKKXXXXXXXKOkxddxONMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWN0dlcoxkOl:dxxxdlcdKXXXXX0doxxxkk0XWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo:coxdcclxO0X0ocllcloOXNXXXXXO:lKNWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl.......,:lxO0XX0kxkKXNNNXXXK0d:cOWNXKXWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxlo,.........,:oxk0KXXXXXK0Okxolll;,c:,'cKMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKcok, ...........,:cloooddocccc:;;,......,0MMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXookdc:cc;................'..............';dNMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0lxOdddddo;..........  .  ...............:dlxNMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKlxOdodddoc..........  .  ...........,clllxklkWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWX0OkkkkOO0XWMMMMMNklddddddl'.......... ..  ...........cxxddk0ooNMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWXkddxxkOOOkxxxxxk0NWMWOc;;;;;,........... .. ...........'cdxddkOloNMMMMMMMMM
MMMMWXKKNWMMMMMMMMMMMWXxoxOXXXXXXNNXXXKOxdxxxxddxc'.............. .. ............'cddddodKMMMMMMMMMM
MWXkdxxxoxXMMMMMMMMMNkld0XXXXNNXXXXXXXXXNXXK00KXXo'.............. .. .............'lxxk0NMMMMMMMMMMM
Nkld0XXKol0MMMMMMMMXdoOXXXXXXXXXXXXXXNNNXNNXNXXXXd;.............  .  .............;KMMMMMMMMMMMMMMMM
xlOXX0xoxKWMMMMMMW0odKXXNXXX0kxxxxxddk0XXXXXXXXXXkl;............ ..  .............dWMMMMMMMMMMMMMMMM
ckXXOldXWMMMMMMMNxlxKXXXKkdddkOKNNNX0xodOXXXXXXXXXX0o,.......... .. .............;0MMMMMMMMMMMMMMMMM
lKNXdoXMMMMMMMNOooOXXXOddxOXWMMMMMMMMMNkod0XXXXXXXXXXKxc,'.....  .  ..........':o0WMMMMMMMMMMMMMMMMM
c0NXxl0WMMMNKkodOXXKkodOXWMMMMMMMMMMMMMMXxlkXXXXXNNXXXXXKOxl,':c::;,;;,,',;:lx0NMMMMMMMMMMMMMMMMMMMM
loKNKxddxxxxdx0XX0xox0WMMMMMMMMMMMMMMMMMMW0dox0XXXNNXXXKOxddkKWWWWWNNNXXKXNWWMMMMMMMMMMMMMMMMMMMMMMM
KdoOXXX0OO0KXXXOdoxKWMMMMMMMMMMMMMMMMMMMMMMWKkxxxxxxxxxxxkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNkodk0KXKK0kxddkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMXxcclcllcld0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
".green.on_black
end
